### ISSUE TITLE
JDK12 Support

### ISSUE THREAD

**Issue by KentoNishi** [rahulkaura2004/tetris_virus#11]
![2019-05-02 (12)](https://user-images.githubusercontent.com/38841491/57119264-9b63d100-6d1d-11e9-9b46-35ff01ebfe7c.png)
JDK12 apparently doesn't have JFX. Maybe add it to the preinstall script?

**Comment by lithomas1** [comment]
Kento, the problem is that javafx is not integrated with JDK anymore after JDK8 so i had to use a custom gradle plugin. If you want to use JDK 12 then you should use the official javafx plugin in your build script, but that won't create a runnable jar even though gradle run will work.

**Comment by KentoNishi** [comment]
Adding JavaFx right now...

**Comment by KentoNishi** [comment]
I installed it to ``C:\javafx-sdk-11.0.2``. I also added the PATH. Now what?
