### ISSUE TITLE
No executable file 

### ISSUE THREAD

**Issue by KentoNishi** [rahulkaura2004/tetris_virus#6]
You need eclipse to run this, but I don't have it installed :P
I have no idea how to use Eclipse. Please make an executable file (like a .jar) so I can run it without building the project.

**Comment by lithomas1** [comment]
Will add gradle, please see the add-jar branch and pull request.

**Comment by Rahul-Kaura** [comment]
No problem!

From,
Rahul

**Comment by KentoNishi** [comment]
@rahulkaura2004 you know how to use Gradle? I thought you don't know how to use git

**Comment by KentoNishi** [comment]
Which jar file after building is supposed to be executed?

**Comment by KentoNishi** [comment]
![image](https://user-images.githubusercontent.com/38841491/57007888-d096e480-6ba0-11e9-94c9-cd128d289e07.png)

**Comment by lithomas1** [comment]
what? i'll fix that but for now you can run code with gradlew build

**Comment by lithomas1** [comment]
should be fixed

**Comment by KentoNishi** [comment]
`gradle build ` j
![image](https://user-images.githubusercontent.com/38841491/57032529-74af7880-6bff-11e9-89b1-834a67f9c36a.png)
what do i do after, it's not doing anything

**Comment by KentoNishi** [comment]
Fix bugs plz
